### ISSUE TITLE
Request: error during execution = default handling

### ISSUE THREAD

**Issue by bradennapier** [wjoye/tclsignal#1]
Would love to have a method of defer the default handling for a signal within execution context.   Such as if an error occurs when executing the callback handler. 

Thanks!  Been wanting a lightweight way to deal with signals for awhile now!  Appreciate it.

**Comment by wjoye** [comment]
Thanks for the note. Yes, it is not perfect, I've really not had time to work on it recently.

The way I'm currently handling errors, is that I have a set of tcl global vars (msg, level, src) which are set/cleared by various parts of the code (tcl, C++) as needed. Then I have a tcl proc which is run once a second, using the 'after' command, looking for changes in these vars. When found, up comes a dialog, instructing the user of the problem and suggested response. For example if my C++ code trips a SEGV, the tcl vars are set, and a dialog informs the user that something serious just happened and best save and restart.

**Comment by bradennapier** [comment]
Couldn't this be accomplished in a much more efficient manner using a trace rather than after?
